const CARDS = [
 {
  "num": 1,
  "name": "Festive Arrival",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Rare",
  "symbol": "LIGHT",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 3.0,
  "atk": 1200.0,
  "def": 1400.0,
  "role": "Deck starter / search engine",
  "image": "01.jpg",
  "setId": "JRD-01",
  "serial": "000000001",
  "effect": "When this card is Normal Summoned: You can add 1 J-Rod card from your Deck to your hand."
 },
 {
  "num": 2,
  "name": "Artistic Reverie",
  "archetype": "J-Rod",
  "category": "Trap",
  "rarity": "Common",
  "symbol": "Trap",
  "race": null,
  "subtype": "Continuous",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Card advantage / mill engine (converted to Trap for balance)",
  "image": "02.jpg",
  "setId": "JRD-02",
  "serial": "000000002",
  "effect": "Once per turn: You can send 1 card from the top of your Deck to the Graveyard; if a J-Rod card is sent this way, draw 1 card."
 },
 {
  "num": 3,
  "name": "Bastion Defender",
  "archetype": "J-Rod",
  "category": "Trap",
  "rarity": "Common",
  "symbol": "Trap",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Defensive stall (converted to Trap for balance)",
  "image": "03.jpg",
  "setId": "JRD-03",
  "serial": "000000003",
  "effect": "When a monster declares an attack: Negate the attack. (Once per turn.)"
 },
 {
  "num": 4,
  "name": "Turbo Racer",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Rare",
  "symbol": "WIND",
  "race": "Machine",
  "subtype": "Effect",
  "level": 4.0,
  "atk": 1800.0,
  "def": 1000.0,
  "role": "Aggro / finisher support",
  "image": "04.jpg",
  "setId": "JRD-04",
  "serial": "000000004",
  "effect": "This card can make a second attack during the Battle Phase, if it destroyed a monster by battle this turn."
 },
 {
  "num": 5,
  "name": "Collector's Joy",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Common",
  "symbol": "LIGHT",
  "race": "Fairy",
  "subtype": "Effect",
  "level": 2.0,
  "atk": 800.0,
  "def": 600.0,
  "role": "Combo enabler / cost reducer",
  "image": "05.jpg",
  "setId": "JRD-05",
  "serial": "000000005",
  "effect": "You can Tribute this card; Special Summon 1 J-Rod monster from your hand or Graveyard, ignoring its Summoning conditions."
 },
 {
  "num": 6,
  "name": "Strike Bowler",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Rare",
  "symbol": "EARTH",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 4.0,
  "atk": 1700.0,
  "def": 1200.0,
  "role": "Backrow removal",
  "image": "06.jpg",
  "setId": "JRD-06",
  "serial": "000000006",
  "effect": "When this card declares an attack: You can destroy 1 Spell/Trap Card your opponent controls."
 },
 {
  "num": 7,
  "name": "Peacock's Grace",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Continuous",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Team-wide ATK buff",
  "image": "07.jpg",
  "setId": "JRD-07",
  "serial": "000000007",
  "effect": "Gain 200 ATK for each face-up J-Rod monster you control. If this card leaves the field, your monsters lose that ATK."
 },
 {
  "num": 8,
  "name": "Velocity Drifter",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Rare",
  "symbol": "WIND",
  "race": "Machine",
  "subtype": "Effect",
  "level": 5.0,
  "atk": 2100.0,
  "def": 1300.0,
  "role": "Mid-game beater / Graveyard payoff",
  "image": "08.jpg",
  "setId": "JRD-08",
  "serial": "000000008",
  "effect": "Gains 100 ATK for each J-Rod monster in your Graveyard."
 },
 {
  "num": 9,
  "name": "Blader's Resolve",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Ultra Rare",
  "symbol": "EARTH",
  "race": "Warrior",
  "subtype": "Effect / Tuner",
  "level": 4.0,
  "atk": 1600.0,
  "def": 1400.0,
  "role": "Tuner \u2014 enables Synchro Summons + Graveyard recursion",
  "image": "09.jpg",
  "setId": "JRD-09",
  "serial": "000000009",
  "effect": "Once per turn: You can Special Summon 1 Level 4 or lower J-Rod monster from your Graveyard."
 },
 {
  "num": 10,
  "name": "The Unbreakable Champion",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Secret Rare",
  "symbol": "EARTH",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 8.0,
  "atk": 2800.0,
  "def": 2400.0,
  "role": "Boss monster / win condition",
  "image": "10.jpg",
  "setId": "JRD-10",
  "serial": "000000010",
  "effect": "Must be Special Summoned by Tributing 2 J-Rod monsters. Cannot be destroyed by battle. Once per turn: Inflict 500 damage to your opponent for each J-Rod monster in your Graveyard."
 },
 {
  "num": 11,
  "name": "Morning Feast",
  "archetype": "J-Rod",
  "category": "Trap",
  "rarity": "Common",
  "symbol": "Trap",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "LP sustain (converted to Trap for balance)",
  "image": "11.jpg",
  "setId": "JRD-11",
  "serial": "000000011",
  "effect": "Banish 1 J-Rod card from your Graveyard; gain 800 LP."
 },
 {
  "num": 12,
  "name": "Gentle Giant",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Rare",
  "symbol": "EARTH",
  "race": "Beast",
  "subtype": "Effect",
  "level": 5.0,
  "atk": 1900.0,
  "def": 2600.0,
  "role": "Tanky protector",
  "image": "12.jpg",
  "setId": "JRD-12",
  "serial": "000000012",
  "effect": "This card cannot be destroyed by card effects. Once per turn: Target 1 other J-Rod monster you control; it cannot be destroyed by battle this turn."
 },
 {
  "num": 13,
  "name": "Bay Breeze",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Combat trick / finishing tool",
  "image": "13.jpg",
  "setId": "JRD-13",
  "serial": "000000013",
  "effect": "Target 1 J-Rod monster you control; it can make a second attack this turn. (Once per turn.)"
 },
 {
  "num": 14,
  "name": "Village Shelter",
  "archetype": "J-Rod",
  "category": "Trap",
  "rarity": "Rare",
  "symbol": "Trap",
  "race": null,
  "subtype": "Continuous",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Protection piece",
  "image": "14.jpg",
  "setId": "JRD-14",
  "serial": "000000014",
  "effect": "Once per turn, when a J-Rod monster you control would be destroyed by battle or card effect: Negate its destruction instead."
 },
 {
  "num": 15,
  "name": "Mango Splash",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Graveyard recursion",
  "image": "15.jpg",
  "setId": "JRD-15",
  "serial": "000000015",
  "effect": "Target 1 J-Rod monster in your Graveyard; Special Summon it in Defense Position. Banish this card when it leaves the field."
 },
 {
  "num": 16,
  "name": "Songbird's Gift",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Common",
  "symbol": "LIGHT",
  "race": "Fairy",
  "subtype": "Effect",
  "level": 2.0,
  "atk": 500.0,
  "def": 500.0,
  "role": "Cheap searcher / discard fodder",
  "image": "16.jpg",
  "setId": "JRD-16",
  "serial": "000000016",
  "effect": "When this card is sent to the Graveyard: You can add 1 Level 4 or lower J-Rod monster from your Deck to your hand."
 },
 {
  "num": 17,
  "name": "Calesa Bond",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Mosaic Rare",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Extra summon / ramp",
  "image": "17.jpg",
  "setId": "JRD-17",
  "serial": "000000017",
  "effect": "Special Summon 1 J-Rod monster from your hand or Deck, but it cannot declare an attack this turn. (Once per turn.)"
 },
 {
  "num": 18,
  "name": "Rice Discovery",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Quick-Play",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Card draw / filtering engine",
  "image": "18.jpg",
  "setId": "JRD-18",
  "serial": "000000018",
  "effect": "Discard 1 card; draw 2 cards. (Once per turn.)"
 },
 {
  "num": 19,
  "name": "Cacao Surge",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Mill + burn damage",
  "image": "19.jpg",
  "setId": "JRD-19",
  "serial": "000000019",
  "effect": "Send the top 3 cards of your Deck to the Graveyard. For each J-Rod card sent this way, inflict 300 damage to your opponent."
 },
 {
  "num": 20,
  "name": "Aura Lights",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Rare",
  "symbol": "Spell",
  "race": null,
  "subtype": "Field",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Field-wide buff + Spell/Trap search",
  "image": "20.jpg",
  "setId": "JRD-20",
  "serial": "000000020",
  "effect": "J-Rod monsters you control gain 300 ATK/DEF. Once per turn: You can add 1 J-Rod Spell/Trap from your Deck to your hand."
 },
 {
  "num": 21,
  "name": "Graduate's Resolve",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Ultra Rare",
  "symbol": "EARTH",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 6.0,
  "atk": 2200.0,
  "def": 1800.0,
  "role": "Mid-late beater / Graveyard-cost boost",
  "image": "21.jpg",
  "setId": "JRD-21",
  "serial": "000000021",
  "effect": "This card can only be Normal Summoned by Tributing 1 J-Rod monster. Once per turn: You can banish 1 J-Rod monster from your Graveyard; this card gains 300 ATK until the End Phase."
 },
 {
  "num": 22,
  "name": "Open Road",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Quick-Play",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Combat trick + card advantage",
  "image": "22.jpg",
  "setId": "JRD-22",
  "serial": "000000022",
  "effect": "Target 1 J-Rod monster you control; it gains 500 ATK until the end of this turn. If it destroys a monster by battle this turn, draw 1 card."
 },
 {
  "num": 23,
  "name": "Young Aspirant",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Rare",
  "symbol": "EARTH",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 2.0,
  "atk": 600.0,
  "def": 400.0,
  "role": "Early-game Spell searcher",
  "image": "23.jpg",
  "setId": "JRD-23",
  "serial": "000000023",
  "effect": "When this card is Normal Summoned: You can add 1 J-Rod Spell from your Deck to your hand. (Once per turn.)"
 },
 {
  "num": 24,
  "name": "Night Out",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Protection trick",
  "image": "24.jpg",
  "setId": "JRD-24",
  "serial": "000000024",
  "effect": "Target 1 J-Rod monster you control; it gains 500 DEF and cannot be targeted by your opponent's card effects this turn."
 },
 {
  "num": 25,
  "name": "Toddler's Spark",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Common",
  "symbol": "LIGHT",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 1.0,
  "atk": 300.0,
  "def": 300.0,
  "role": "Cheap combo fodder / ramp",
  "image": "25.jpg",
  "setId": "JRD-25",
  "serial": "000000025",
  "effect": "You can Tribute this card; Special Summon 1 J-Rod monster from your hand, ignoring its Summoning conditions, except \"Toddler's Spark.\""
 },
 {
  "num": 26,
  "name": "Brothers' Bond",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Rainbow Rare",
  "symbol": "EARTH",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 4.0,
  "atk": 1600.0,
  "def": 1600.0,
  "role": "Go-wide payoff",
  "image": "26.jpg",
  "setId": "JRD-26",
  "serial": "000000026",
  "effect": "While you control 2 or more other J-Rod monsters, this card gains 800 ATK/DEF."
 },
 {
  "num": 27,
  "name": "Sharp-Dressed Veteran",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Secret Rare",
  "symbol": "EARTH",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 7.0,
  "atk": 2500.0,
  "def": 2000.0,
  "role": "Late-game removal beater",
  "image": "27.jpg",
  "setId": "JRD-27",
  "serial": "000000027",
  "effect": "Cannot be Normal Summoned/Set. Must be Special Summoned by banishing 1 J-Rod monster from your Graveyard. Once per turn: Target 1 card on the field; destroy it."
 },
 {
  "num": 28,
  "name": "Piki the Hungry",
  "archetype": "Birbs",
  "category": "Monster",
  "rarity": "Rare",
  "symbol": "WIND",
  "race": "Winged Beast",
  "subtype": "Effect",
  "level": 1.0,
  "atk": 100.0,
  "def": 100.0,
  "role": "Flock recursion / search",
  "image": "28.jpg",
  "setId": "BRB-28",
  "serial": "000000028",
  "effect": "If this card is in your Graveyard: You can banish it; add 1 Birb card from your Deck to your hand. (Once per turn.)"
 },
 {
  "num": 29,
  "name": "Pastel the First",
  "archetype": "Birbs",
  "category": "Monster",
  "rarity": "Rainbow Rare",
  "symbol": "WIND",
  "race": "Winged Beast",
  "subtype": "Effect",
  "level": 1.0,
  "atk": 0.0,
  "def": 1800.0,
  "role": "Flock protector / defensive anchor",
  "image": "29.jpg",
  "setId": "BRB-29",
  "serial": "000000029",
  "effect": "While this card is on the field, Birb monsters you control cannot be destroyed by battle."
 },
 {
  "num": 30,
  "name": "Will the Refreshed",
  "archetype": "Birbs",
  "category": "Trap",
  "rarity": "Common",
  "symbol": "Trap",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Flock LP gain (converted to Trap for balance)",
  "image": "30.jpg",
  "setId": "BRB-30",
  "serial": "000000030",
  "effect": "Send 1 Birb card from your hand to the Graveyard; gain 500 LP."
 },
 {
  "num": 31,
  "name": "Keeper of Curiosities",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Continuous",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Resource recovery (converted to Spell for balance)",
  "image": "31.jpg",
  "setId": "JRD-31",
  "serial": "000000031",
  "effect": "Once per turn: You can pay 500 LP; add 1 J-Rod or Birb card from your Graveyard to your hand."
 },
 {
  "num": 32,
  "name": "Monday's Mood",
  "archetype": "J-Rod",
  "category": "Trap",
  "rarity": "Common",
  "symbol": "Trap",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Ambush defender (converted to Trap for balance)",
  "image": "32.jpg",
  "setId": "JRD-32",
  "serial": "000000032",
  "effect": "Activate when your opponent declares an attack: Target 1 face-up Attack Position J-Rod monster you control; it gains 500 ATK until the end of this turn."
 },
 {
  "num": 33,
  "name": "Fresh Start",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Graveyard reset / draw smoother (converted to Spell for balance)",
  "image": "33.jpg",
  "setId": "JRD-33",
  "serial": "000000033",
  "effect": "Shuffle 1 card from your Graveyard into the Deck; if you do, draw 1 card."
 },
 {
  "num": 34,
  "name": "Piki's Joyride",
  "archetype": "Birbs",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Flock extender / swarm tool",
  "image": "34.jpg",
  "setId": "BRB-34",
  "serial": "000000034",
  "effect": "Target 1 Birb monster you control; Special Summon 1 Birb monster with the same Level from your Deck. (Once per turn.)"
 },
 {
  "num": 35,
  "name": "Piki the Adventurer",
  "archetype": "Birbs",
  "category": "Monster",
  "rarity": "Rare",
  "symbol": "WIND",
  "race": "Winged Beast",
  "subtype": "Effect",
  "level": 2.0,
  "atk": 400.0,
  "def": 800.0,
  "role": "Direct damage for go-wide Flock boards",
  "image": "35.jpg",
  "setId": "BRB-35",
  "serial": "000000035",
  "effect": "If you control another Birb monster: This card can attack directly."
 },
 {
  "num": 36,
  "name": "The Audiophile",
  "archetype": "J-Rod",
  "category": "Trap",
  "rarity": "Common",
  "symbol": "Trap",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Bounce / disruption tool (converted to Trap for balance)",
  "image": "36.jpg",
  "setId": "JRD-36",
  "serial": "000000036",
  "effect": "Target 1 Spell/Trap on the field; return it to the hand."
 },
 {
  "num": 37,
  "name": "Lazy Morning",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Smoothing / low-cost card flow",
  "image": "37.jpg",
  "setId": "JRD-37",
  "serial": "000000037",
  "effect": "Draw 2 cards, then place 1 card from your hand on top of your Deck."
 },
 {
  "num": 38,
  "name": "Steam & Resolve",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Rare",
  "symbol": "FIRE",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 4.0,
  "atk": 1800.0,
  "def": 1200.0,
  "role": "Aggro burn support",
  "image": "38.jpg",
  "setId": "JRD-38",
  "serial": "000000038",
  "effect": "If this card battles an opponent's monster: After damage calculation, inflict 300 damage to your opponent."
 },
 {
  "num": 39,
  "name": "Piki & Will, Cage Mates",
  "archetype": "Birbs",
  "category": "Monster",
  "rarity": "Shatterfoil Rare",
  "symbol": "WIND",
  "race": "Winged Beast",
  "subtype": "Effect",
  "level": 3.0,
  "atk": 800.0,
  "def": 1200.0,
  "role": "Dual-named searcher, flexible support",
  "image": "39.jpg",
  "setId": "BRB-39",
  "serial": "000000039",
  "effect": "This card's name is treated as both \"Piki\" and \"Will\" while on the field or in the Graveyard. If Normal Summoned: You can add 1 Level 1 Birb monster from your Deck to your hand."
 },
 {
  "num": 40,
  "name": "The Dreamer",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Ultra Rare",
  "symbol": "DARK",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 1.0,
  "atk": 0.0,
  "def": 0.0,
  "role": "Resilient Level 1 engine / combo material",
  "image": "40.jpg",
  "setId": "JRD-40",
  "serial": "000000040",
  "effect": "Cannot be destroyed by battle. Once per turn, during your Standby Phase: You can add 1 J-Rod card from your Deck to your hand, then send the top card of your Deck to the Graveyard."
 },
 {
  "num": 41,
  "name": "Winter Guardian",
  "archetype": "J-Rod",
  "category": "Trap",
  "rarity": "Common",
  "symbol": "Trap",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Defensive trick (converted to Trap for balance)",
  "image": "41.jpg",
  "setId": "JRD-41",
  "serial": "000000041",
  "effect": "Target 1 J-Rod monster you control in Defense Position; it gains 500 DEF until the end of this turn."
 },
 {
  "num": 42,
  "name": "Sweetheart Charm",
  "archetype": "J-Rod",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Light protection + LP gain",
  "image": "42.jpg",
  "setId": "JRD-42",
  "serial": "000000042",
  "effect": "Target 1 J-Rod monster you control; it cannot be destroyed by your opponent's card effects this turn. Gain 400 LP."
 },
 {
  "num": 43,
  "name": "Night Train",
  "archetype": "J-Rod",
  "category": "Trap",
  "rarity": "Rare",
  "symbol": "Trap",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Recycling + backrow setup (converted to Trap for balance)",
  "image": "43.jpg",
  "setId": "JRD-43",
  "serial": "000000043",
  "effect": "Set 1 J-Rod Spell/Trap from your Deck to your Spell & Trap Zone, then you can shuffle 1 J-Rod card from your Graveyard into the Deck."
 },
 {
  "num": 44,
  "name": "Flock Photographer",
  "archetype": "J-Rod / Birbs",
  "category": "Monster",
  "rarity": "Shatterfoil Rare",
  "symbol": "LIGHT",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 4.0,
  "atk": 1500.0,
  "def": 1500.0,
  "role": "Bridge card between J-Rod and Birbs",
  "image": "44.jpg",
  "setId": "JRD-44",
  "serial": "000000044",
  "effect": "When this card is Normal Summoned: You can add 1 Birb monster from your Deck to your hand. If you control 2 or more Birb monsters: This card gains 500 ATK."
 },
 {
  "num": 45,
  "name": "Cherished Gift",
  "archetype": "J-Rod / Birbs",
  "category": "Spell",
  "rarity": "Mosaic Rare",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Birbs ramp / extender",
  "image": "45.jpg",
  "setId": "JRD-45",
  "serial": "000000045",
  "effect": "Special Summon 1 Birb monster from your Deck in Defense Position. (Once per turn.)"
 },
 {
  "num": 46,
  "name": "Piki's Affection",
  "archetype": "Birbs",
  "category": "Trap",
  "rarity": "Rare",
  "symbol": "Trap",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Protection tool for main archetype (converted to Trap for balance)",
  "image": "46.jpg",
  "setId": "BRB-46",
  "serial": "000000046",
  "effect": "Your opponent cannot target J-Rod monsters you control with card effects until your next Standby Phase."
 },
 {
  "num": 47,
  "name": "Iron Will",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Ultra Rare",
  "symbol": "EARTH",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 5.0,
  "atk": 2000.0,
  "def": 1700.0,
  "role": "Go-wide payoff beater",
  "image": "47.jpg",
  "setId": "JRD-47",
  "serial": "000000047",
  "effect": "This card gains 200 ATK for each other J-Rod monster you control."
 },
 {
  "num": 48,
  "name": "Silly Snack Break",
  "archetype": "J-Rod / Birbs",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Filtering with Birbs synerGraveyard bonus",
  "image": "48.jpg",
  "setId": "JRD-48",
  "serial": "000000048",
  "effect": "Discard 1 J-Rod or Birb card; draw 1 card. If the discarded card was a Birb card, draw 1 additional card."
 },
 {
  "num": 49,
  "name": "All Good Here",
  "archetype": "J-Rod",
  "category": "Trap",
  "rarity": "Common",
  "symbol": "Trap",
  "race": null,
  "subtype": "Counter",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Damage negation (converted to Counter Trap for balance)",
  "image": "49.jpg",
  "setId": "JRD-49",
  "serial": "000000049",
  "effect": "When an effect that would inflict damage to you is activated: Negate that effect."
 },
 {
  "num": 50,
  "name": "Piki, the Watchful",
  "archetype": "Birbs",
  "category": "Trap",
  "rarity": "Common",
  "symbol": "Trap",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Hand disruption (converted to Trap for balance)",
  "image": "50.jpg",
  "setId": "BRB-50",
  "serial": "000000050",
  "effect": "Look at your opponent's hand. If a Trap Card is revealed this way: Destroy it."
 },
 {
  "num": 51,
  "name": "Will, the Sideways Glance",
  "archetype": "Birbs",
  "category": "Monster",
  "rarity": "Common",
  "symbol": "WIND",
  "race": "Winged Beast",
  "subtype": "Effect",
  "level": 1.0,
  "atk": 100.0,
  "def": 700.0,
  "role": "Flock searcher / easy recursion",
  "image": "51.jpg",
  "setId": "BRB-51",
  "serial": "000000051",
  "effect": "Once per turn: You can change this card to face-up Defense Position. If you do: Add 1 Level 1 monster from your Deck to your hand."
 },
 {
  "num": 52,
  "name": "Crimson Cruiser",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Ultra Rare",
  "symbol": "FIRE",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 4.0,
  "atk": 1900.0,
  "def": 1100.0,
  "role": "Aggro / double-attacker finisher",
  "image": "52.jpg",
  "setId": "JRD-52",
  "serial": "000000052",
  "effect": "Once per turn, during the Battle Phase: This card can attack twice. (Hard once-per-turn.)"
 },
 {
  "num": 53,
  "name": "Pastel's Quiet Walk",
  "archetype": "Birbs",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Searcher with small bonus",
  "image": "53.jpg",
  "setId": "BRB-53",
  "serial": "000000053",
  "effect": "Add 1 Level 1 Birb monster from your Deck to your hand. If the monster added this way is named \"Pastel,\" also gain 300 LP."
 },
 {
  "num": 54,
  "name": "Sparkjoy Collector",
  "archetype": "J-Rod / Birbs",
  "category": "Monster",
  "rarity": "Rare",
  "symbol": "LIGHT",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 4.0,
  "atk": 1600.0,
  "def": 1400.0,
  "role": "Bridge searcher (J-Rod into Birbs)",
  "image": "54.jpg",
  "setId": "JRD-54",
  "serial": "000000054",
  "effect": "When this card is Normal Summoned: You can add 1 Birb monster with 800 or less ATK from your Deck to your hand."
 },
 {
  "num": 55,
  "name": "Focused Striker",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Ultra Rare",
  "symbol": "EARTH",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 5.0,
  "atk": 2100.0,
  "def": 1500.0,
  "role": "Disruption-proof beater with piercing",
  "image": "55.jpg",
  "setId": "JRD-55",
  "serial": "000000055",
  "effect": "This card cannot be targeted by Spell/Trap effects. Once per turn, if this card attacks a Defense Position monster: Inflict 200 piercing damage."
 },
 {
  "num": 56,
  "name": "Night Ritual",
  "archetype": "J-Rod / Birbs",
  "category": "Spell",
  "rarity": "Common",
  "symbol": "Spell",
  "race": null,
  "subtype": "Continuous",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Steady recursion engine for both sub-themes",
  "image": "56.jpg",
  "setId": "JRD-56",
  "serial": "000000056",
  "effect": "Once per turn: You can send 1 card from your hand to the Graveyard; if you do, add 1 J-Rod or Birb card from your Graveyard to your hand."
 },
 {
  "num": 57,
  "name": "Hidden Under the Sheets",
  "archetype": "Birbs",
  "category": "Trap",
  "rarity": "Common",
  "symbol": "Trap",
  "race": null,
  "subtype": "Normal",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Temporary removal / tempo trap",
  "image": "57.jpg",
  "setId": "BRB-57",
  "serial": "000000057",
  "effect": "Target 1 monster your opponent controls with 1500 or less ATK; banish it face-down until the End Phase."
 },
 {
  "num": 58,
  "name": "Poised Reflection",
  "archetype": "J-Rod",
  "category": "Trap",
  "rarity": "Common",
  "symbol": "Trap",
  "race": null,
  "subtype": "Counter",
  "level": null,
  "atk": null,
  "def": null,
  "role": "Protection (converted to Counter Trap for balance)",
  "image": "58.jpg",
  "setId": "JRD-58",
  "serial": "000000058",
  "effect": "When a J-Rod monster you control is targeted by an opponent's card effect: Negate that effect."
 },
 {
  "num": 59,
  "name": "Floor-Level Focus",
  "archetype": "J-Rod",
  "category": "Monster",
  "rarity": "Rare",
  "symbol": "EARTH",
  "race": "Warrior",
  "subtype": "Effect",
  "level": 3.0,
  "atk": 1200.0,
  "def": 1800.0,
  "role": "Defensive wall with flip recursion",
  "image": "59.jpg",
  "setId": "JRD-59",
  "serial": "000000059",
  "effect": "This card cannot be destroyed by battle while in Defense Position. When this card is flipped face-up: Special Summon 1 Level 4 or lower J-Rod monster from your Graveyard."
 },
 {
  "num": 60,
  "name": "Piki's Devoted Companion",
  "archetype": "Birbs",
  "category": "Monster",
  "rarity": "Secret Rare",
  "symbol": "LIGHT",
  "race": "Winged Beast",
  "subtype": "Effect",
  "level": 7.0,
  "atk": 2400.0,
  "def": 2000.0,
  "role": "Birbs' boss monster \u2014 bonds with J-Rod side too",
  "image": "60.jpg",
  "setId": "BRB-60",
  "serial": "000000060",
  "effect": "Cannot be Normal Summoned/Set. Must be Special Summoned by banishing 2 Birb monsters from your Graveyard. Once per turn: Target 1 J-Rod monster you control; it gains 600 ATK/DEF until the end of this turn. If this card is destroyed: You can add 1 Birb monster from your Deck to your hand."
 }
];